version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - sqlite_data:/transcription.db
    environment:
      - PROJECT_NAME=Audio Sample TA
      - ENVIRONMENT=production
      - BACKEND_CORS_ORIGINS=["http://localhost:5173"]
    restart: unless-stopped

volumes:
  sqlite_data: 